### PR TITLE
Updated MUN'25 branding and navigation links in header

### PR DESCRIPTION
**Pull request by mr-raj12**
This PR introduces the following updates to the repository:

Branding Changes: Rebranded "Genesis" to "Bitmun," retaining the original inspiration while adopting a fresh color scheme.
Header Updates: Added navigation links for the Recruitment and About Us sections to enhance accessibility.
These changes improve the website's visual identity and user experience while maintaining alignment with its original design.

Key Benefits:
Enhanced user navigation with functional and intuitive links.
Modernized branding with a refreshed color palette.
Please review the changes and let me know if further adjustments are required!

### CODE REVIEW

**Comment by mr-raj12** [comment]
Fixed the horizontal overflow issue by adding

**Comment by mr-raj12** [comment]
Implemented registration buttons for /bitmun page

**Comment by MasterK0927** [comment]
Just fix the about us button and remove the emojis from the alert. Then we are good to merge

**Comment by mr-raj12** [comment]
Fixed the alignment of the 'About Us' button and removed emojis from the alert as requested. Let me know if there's anything else to tweak!

**Review by MasterK0927 — APPROVED** [review]

**Pull request merged**
